### ISSUE TITLE
INVALID_SIGNATURE issue

### ISSUE THREAD

**Issue by dr20240304** [wensheng/hedera-sdk-py#12]
`python3 ./examples/transfer_crypto.py    
0.0.3  balance =  118372.53922308 ℏ
0.0.3  balance =  118372.53922308 ℏ
Traceback (most recent call last):
  File "/hedera-sdk-py/./examples/transfer_crypto.py", line 23, in <module>
    ).execute(client)
      ^^^^^^^^^^^^^^^
  File "jnius/jnius_export_class.pxi", line 1163, in jnius.JavaMultipleMethod.__call__
  File "jnius/jnius_export_class.pxi", line 877, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 954, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 79, in jnius.check_exception
jnius.JavaException: JVM exception occurred: Hedera transaction `0.0.3@1731344758.830000000` failed pre-check with the status `INVALID_SIGNATURE` com.hedera.hashgraph.sdk.PrecheckStatusException`

Any solution for this error?

**Comment by wensheng** [comment]
could not duplicate, please try latest version.
